spec_version: 2
name: qr-code-generator
region: fra
features:
  - buildpack-stack=ubuntu-22

functions:
  - name: api
    source_dir: /
    github:
      deploy_on_push: true
      branch: main
    routes:
      - path: /
        preserve_path_prefix: false
